---
title: "surface_water"
output: html_document
---

```{r}

rm(list=ls()) # Clear working environment
setwd("/Users/stubbsrw/Documents/fe_problems") # Set working directory

library("MapSuite") #Self-written library, has many common libs as dependencies
library("hexbin") # For the hex-bin plots

sw<-fread("/Users/stubbsrw/Documents/git_code/stubbs_repo/fe_problems/data/Dataset_C.csv") # surface water observations

sw[,index:=seq(1:nrow(sw))]
# Parse out date information from character date column
sw[,Month:=as.numeric(strsplit(SampleDate,"/")[[1]][1]),by=index]
sw[,Day:=as.numeric(strsplit(SampleDate,"/")[[1]][2]),by=index]
sw[,Year:=as.numeric(strsplit(SampleDate,"/")[[1]][3]),by=index]
sw[,Date:=as.IDate(paste0((2000+Year),"-",Month,"-",Day))] # Create formal column of integer-date

# For each analyte, discover the minimum date, and generate a month index from that date:
sw[,year_min:=min(Year,na.rm=T),by=StandardAnalyte] # First sample year, calculated by each analyte
sw[,month_index:=(12*Year-year_min) + Month] # Number of months from the start of the samples

# Add variables on mean concentration for each analyte by site and globally/for all samples
sw[,mean_concentration_analyte_station:=mean(StandardResult,na.rm=T),by=list(StationName,StandardAnalyte)]
sw[,mean_concentration_analyte:=mean(StandardResult,na.rm=T),by=StandardAnalyte]

```

## Assign seasons to different months

Worth noting here that you could do this a fancier way if you wanted, based on cut points of the equinoxes; for now, we'll just go by month approximations. I'm also assuming that this is in the Northern hemisphere..

```{r}
sw[Month %in% c(12,1,2), Season:='Winter']
sw[Month %in% c(3,4,5), Season:='Spring']
sw[Month %in% c(6,7,8), Season:='Summer']
sw[Month %in% c(9,10,11), Season:='Fall']
sw[,Month_String:=month.abb[Month]]
sw[,log_obs:=log(StandardResult)]
```
Do a test plot: 1 Analyte, 1 Station, over time. 

```{r}
a<-"Oxygen, Dissolved"
s<-"FE-4023"
analyte<-sw[StandardAnalyte==a]
mean_observation<-mean(analyte$StandardResult)

ggplot(analyte, aes(x= Date, y=StandardResult, color=StationName)) + geom_hex() + xlab("") + ylab(analyte$StandardUnit[1]) + ggtitle(a) + scale_x_date(labels = function(x) format(x, "%b-%y"))


# Plotting using the HexBin Frequency graphics, where the number of stations 
ggplot(analyte, aes(x=Date, y=log_obs)) + 
  geom_hex() + 
  xlab("Observations in Each Month, All Years, All Stations") + 
  scale_x_date(labels = function(x) format(x, "%b-%y")) + 
  ylab(analyte$StandardUnit[1]) + 
  ggtitle(paste0(a)) + theme_bw() + 
  scale_fill_gradientn(colors=wpal("cool_blue_jeans")) +
  guides(fill=guide_colourbar(title="N Stations", title.position="top", barheight=10, barwidth=1,
                              label=TRUE, ticks=FALSE, direction="vertical")) 

# Plotting by Month, for all years, all stations 
months_in_order<-c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")

# Non-Transformed
ggplot(analyte, aes(x= Month, y=log_obs)) + geom_hex() + 
  xlab("Observations in Each Month, All Years, All Stations") + 
  scale_x_continuous(limits=c(1,12),breaks=seq(1,12), labels=months_in_order) +
  ylab(analyte$StandardUnit[1]) + 
  ggtitle(paste0(a)) + theme_bw() + 
  scale_fill_gradientn(colors=wpal("berries")) +
  guides(fill=guide_colourbar(title="N Stations", title.position="top", barheight=10, barwidth=1,
                              label=TRUE, ticks=FALSE, direction="vertical")) 

# Log-transformed
ggplot(analyte, aes(x= Month, y=log_obs)) + geom_hex() + 
  xlab("Observations in Each Month, All Years, All Stations") + 
  scale_x_continuous(limits=c(1,12),breaks=seq(1,12), labels=months_in_order) +
  ylab(analyte$StandardUnit[1]) + 
  ggtitle(paste0(a," (Log-Transformed) ")) + theme_bw() + 
  scale_fill_gradientn(colors=wpal("berries")) +
  guides(fill=guide_colourbar(title="N Stations", title.position="top", barheight=10, barwidth=1,
                              label=TRUE, ticks=FALSE, direction="vertical")) 

```

## Plot by Station, Analyte. 

```{r}
for (s in unique(sw$StationName)){
for ( a in unique(StatndardAnalyte)){

}
}
```

## Fit GAMM with knots for each season and year

```{r}
# Pulling from https://www.fromthebottomoftheheap.net/2014/05/09/modelling-seasonal-data-with-gam/
# 4 Seasons, 3 Years.
m0 <- mgcv::gamm(StandardResult ~ s(Month, bs = "cc", k = 4) + s(month_index, k = 3) + as.factor(StationName), data = analyte)

plot(m0$gam, scale = 0, main = "GAMM fit", xlab = "Month", ylab = paste0(a," Seasonal Effect"))

```


